---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
      - recipe[locale]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[locale]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[locale]
  - name: debian-6.0.8
    run_list:
      - recipe[apt]
      - recipe[locale]
  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[locale]
  - name: centos-5.10
  - name: centos-6.4
  - name: centos-7.0


suites:
  - name: default
    run_list:
        - recipe[postgresql::default]
    attributes:
        #postgresql:
        #    version: "9.2"
