---
driver:
   name: ec2
   aws_ssh_key_id: <%= ENV['AWS_VAGRANT_SSH_KEY_NAME'] %>
   availability_zone: us-east-1d
   associate_public_ip: true

transport:
    ssh_key: <%= ENV['AWS_VAGRANT_SSH_KEY'] %>
    interface: public
    ssh_retries: 10

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: Amazon-Linux-2014-09
  driver_plugin: ec2
  driver_config:
    image_id: ami-50842d38 

- name: Amazon-Linux-201403
  driver_plugin: ec2
  driver_config:
    image_id: ami-d2817cba

- name: Amazon-Linux-201503
  driver_plugin: ec2
  driver_config:
    instance_type: m3.medium
    image_id: ami-5231103a

- name: RHEL7
  driver_plugin: ec2
  driver_config:
    image_id: ami-785bae10
    instance_type: m3.medium

- name: Ubuntu-16-04
  driver_plugin: ec2
  driver_config:
      image_id: ami-c45b54ae
      instance_type: m3.medium
      subnet_id: subnet-1c938645
  transport:
      username: ubuntu

suites:
- name: default
  run_list:
      - recipe[apache2::default]
  attributes:
