---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: debian-6.0.8
    run_list:
      - recipe[apt]
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: centos-5.10
  - name: centos-6.4


suites:
  - name: stable
    run_list:
        - recipe[scalarizr::default]
    attributes:
        scalarizr:
            branch: "stable"
  - name: candidate
    run_list:
        - recipe[scalarizr::default]
    attributes:
        scalarizr:
            branch: "candidate"
  - name: latest
    run_list:
        - recipe[scalarizr::default]
    attributes:
        scalarizr:
            branch: "latest"
  - name: feature-SCALARIZR-1617
    run_list:
        - recipe[scalarizr::default]
    attributes:
        scalarizr:
            branch: "feature-SCALARIZR-1617"
